licenses([
    "reciprocal",  # Eclipse Public License - v 1.0
])

load("//build_def:j2cl_library.bzl", "j2cl_library")

java_library(
    name = "junit_emul",
    srcs = glob(["*.java"]),
#    deps = ["//jre/java:jre"]
)